# docker-compose.yml
version: "3.8"
services:
  anime-tip:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - anime-tip-data:/data
    environment:
      - PORT=8080
      - CHECK_INTERVAL=0 * * * *
      - SERVER_CHAN_KEY=
      - VOD_BASE_URL=https://cj.lziapi.com
    restart: unless-stopped

volumes:
  anime-tip-data:
